### ISSUE TITLE
Audit

### ISSUE THREAD

**Issue by samczsun** [mudgen/mokens-bug-bounty#1]
Pretty good. Only found one issue. I'm curious what the purpose of storing the link hash is, and what prevents me from changing my link hash to that of another moken.

Also, I would strongly recommend against implementing the price buffer. Why would people pay full price when they can get a discount?

### Illegal characters can be used
The range for a byte is `0x00` to `0xff`. This gives me a lot of [whitespace characters](https://unicode-table.com/en/) to choose from, as well as random symbols like `©`

**Comment by mudgen** [comment]
Hi @samczsun, 

I looked into your claim that illegal characters can be used and I found it to be valid. Good work! Please send me your ethereum address and after the bug bounty I will send you ETH. Thank you very much for your report!

As for a solution to this, here's my thoughts:
I want people to be able to create moken names using languages beside English, so I don't want to restrict the the valid characters to only English letters, punctuation, space and numbers.

I do not see an efficient way to prevent all whitespace/non-printable characters (other than space) from being used and at the same time allowing non-English characters.

Here's my multi-part solution:
1. The Mokens Contract will only prevent some non-printing and whitespace characters in moken names.
2. mokens can rely on the [forgery system](https://mokens.io/about/forgery-system) to detect moken names that use whitespace to try to look like earlier moken names.
3. I will add further validation to the [mokens mint](https://mokens.io/) form so that it prevents whitespace/non-printable characters (other than space between letters) from being used. 
4. I will display a warning on the moken webpages on moken.io for each moken that uses whitespace/non-printable characters (other than the space character that is used between letters), saying that the moken may be a forgery. This is for mokens that are minted not using the mokens.io mint form.

### Edit
I thought about it more.  Maybe only ASCII should be allowed in moken names. That is doable and would help keep moken names simple and unique.  But then moken names could not be in non-English languages. Thoughts anyone?

I will address your suggestion about the price buffer and your question about the link hash in my next replies.

**Comment by mudgen** [comment]
### About the link hash

The purpose of a link hash is to validate that certain off-chain data belongs to a moken, as determined by the owner of the moken.

Somebody, anybody, could display a moken somewhere on the web. The moken Id, the moken name, the moken description, the moken image and possibly other data could be displayed for the moken. Specifically the moken id and name identifies a moken in the Mokens Contract. But how would you verify that the moken description and moken image and possibly other off-chain data actually belong to that moken as specified by the owner of that moken?  You would make a hash of that data and see if it matches the link hash of the moken from the contract.  The link hash gives a way to verify that off chain data belongs to a moken as specified by the owner of the moken.

Yes, the owner of a moken can change the link hash. This allows owners of mokens to change/upgrade/improve the display and off-chain data of their mokens.

If an owner of a moken changed the link hash of their moken to be the same as another moken and tried to make their moken about the exact same thing as an existing one, then that moken would be labeled as a forgery on the mokens.io website. In the future I also want to create a contract that holds a registry of forgery mokens so it can be used by other contracts and dapps.

**Comment by mudgen** [comment]
## About the price buffer

Each time a new moken is minted the price to mint a moken goes up by the amount specified by mintStepPrice. What happens if two or more people try to mint a moken at the same time? They see the same price so they both try to mint a moken at the same price. One of the transactions will go through at that price and the other transaction will fail because the price went up. But if there is a price buffer then the second transaction can still succeed.

@samczsun, you are right that people can try to cheat the system by taking advantage of the mintPriceBuffer but there are a few factors that mitigate this. Here they are:

1. Most people have a kind, non-cheating heart.
2. The mokens.io website only lets people mint mokens at the current price. Though people are encouraged to use other websites and tools to mint mokens and I can help with integration.
2. As the price to mint mokens rises the theft that is possible with mintPriceBuffer matters less. Currently mintPriceBuffer is set to 0.01 ETH which is about $5.50 USD. So that is the largest discount possible but that stays the same as the mint price rises with each mint. At the beginning it is possible to cheat with a steep discount, but after 300 mokens have been minted the price to mint a moken will be 0.16 ETH which is $87.63 USD, and the discount that will be possible will still be $5.50.

I am open to other ideas/suggestions about how to implement the mint functionality so that the price increases after each mint, but people's transactions are not rejected because the price changed on them.

**Comment by samczsun** [comment]
Thanks!

Regarding whitespace characters, I suppose you could just allow all characters, then add some logic on the frontend which displays all non-printable and/or intentionally misleading characters as their unicode escape sequence. Unicode is hard enough as it is, and the gas limit makes complex logic impossible.

Instead of using a link hash, why not have the owner of the moken sign something like "I, <address>, claim <data> is associated with <moken>"? That's off-chain, so it's free, and makes it so instead of a moken declaring that it belongs to someone, the owner declares that they own a moken. That's one type of forgery you don't need to worry about anymore.

As for the price buffer, I think your best option is to make it clear to the user that at times of high demand prices may increase between time of transaction submitted and time of transaction mined, then offer the ability to pay a higher price and get a refund. This is because while most people are pretty nice and won't try to cheat, all it takes is one person. (Writing a bot or just using Remix to call the contract directly isn't exactly difficult either).

As an example, if you look at the code for CryptoKitties you'll see that there's a 0.08eth fee that you can collect for helping birth a kitty. After gas and whatever you get less than 0.01eth back (or something small like that) but there's still a handful of bots going at it because free money is free money. If mokens become the next cryptokitties, then why _wouldn't_ I buy up a bunch of mokens at a discount and sell them at regular price? It's still free money.

**Comment by mudgen** [comment]
Hi samczun,

Yes, I agree that letting the frontend handle the characters is the answer as you mentioned. It will be as you mentioned.

I think you are right that having the user sign a message in order to change off-chain data is a good idea and the right way to do it. 

I was looking at removing the linkHash functionality and I remembered/ran into another reason I have it. It has to do with submitting the [moken form](https://mokens.io) to make a moken. When a user submits the form the moken data gets stored in my database, including the linkHash data. When the mint event from the  Mokens Contract fires, my backend catches it and uses the moken name and owner address and the linkHash to find the off-chain data in my database so that the off-chain data and the moken can be tied together. Without the linkHash I can't be certain that I associate the right off-chain data when a moken is minted. Does this make sense?  When a moken transaction is mined the mint event fires and I then need to associate that moken with its offchain data in my database, and using the linkHash is an important part of that. I would like to get rid of the linkHash, so if you have an idea about solving this then I appreciate you telling me.

It makes sense what you are saying about the price buffer. But it adds a barrier/confusion/complexity for users if they have to understand that their transaction might not go through because the price could change. I'd rather users not have to think about that and their transactions always go through.

But I do see what you are saying and I see that it is possible that people and/or bots try to take advantage of the price buffer so I'm reducing the price buffer from 0.01 ETH to 0.005 ETH. If it is a problem in the future I can switch to the exact strategy you mentioned:  I can set the price buffer to 0 using the setMintPrice function and start telling people to pay a bit more than the current price to avoid their transactions from failing and that they will get a refund if they overpay. The functionality to pay back a refund if someone pays over the current price is already implemented in the mint function.

**Comment by samczsun** [comment]
That should be a relatively simple problem to solve. If I understand correctly, the following setup should work fine. First, have a table of mokens, with the moken id being the primary key. The moken table should contain all the off-chain data related to the moken, as well as an owner address. People can claim ownership of a moken with a specific id by signing a message from the owning address.

The price buffer compromise sounds good. As long as you're aware of the risks of allowing users to gain an 'unfair' advantage then that's better than not being aware at all

**Comment by mudgen** [comment]
Eth sent.
