### ISSUE TITLE
SafeMath

### ISSUE THREAD

**Issue by nigeon** [mudgen/mokens-bug-bounty#2]
Just a fast checking the code realized you are not using [SafeMath](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/math/SafeMath.sol) or any other library to avoid **over/underflows.**

As you may know, this can be really dangerous. [More info](https://medium.com/loom-network/how-to-secure-your-smart-contracts-6-solidity-vulnerabilities-and-how-to-avoid-them-part-1-c33048d4d17d).

**Couple of examples:**
- setMintPrice() method
`mintPrice = _mintBasePrice + (mokensLength * _mintStepPrice);`
**mokensLength** it's a uint that eventually will reach a high number, overflowing **mintPrice**.

- mint() method
`uint256 currentMintPrice = mintBasePrice + (tokenId * mintStepPrice_);`
**currentMintPrice** could eventually overflow when tokenId is big enough. This overflow will make useless the following check `if(msg.value < currentMintPrice) {`

Some of the methods with possible over/underflows are onlyManager, but still, it might be a good practice to use the [SafeMath](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/math/SafeMath.sol) library.

**Comment by mudgen** [comment]
Hi @nigeon, thank you for looking at the contract and for your report!

I am aware of SafeMath and agree it is good practice to use it. However for this contract I want to take care of overflows and underflows myself. The examples you gave would only overflow or underflow if I messed up and gave mintStepPrice or mintBasePrice completely wrong values, which is very unlikely.  But still, I think it is good to add more safety if I can. So I am improving this. Thanks for telling me about this. Please send me your ethereum address and I will send you some ETH when the bug bounty program is over.

When looking at this I realized that `currentMintPrice = mintBasePrice + (tokenId * mintStepPrice_);` is inflexible. The only way to drastically lower the current price while keeping the mintStepPrice the same is by intentionally overflowing `mintBasePrice + (tokenId * mintStepPrice_)` by giving mintBasePrice a very big value and that doesn't seem like a good way to use integers. I'm afraid the solidity team might add automatic integer overflow handing/checking in the future.

So I changed the way the current price is calculated and updated the source code. I replaced mintBasePrice with mintPriceOffset and the new formula to calculate the current price is this: `uint256 currentMintPrice = (mokensLength * mintStepPrice) - mintPriceOffset`

I appreciate you looking again at this area of code because it has these new changes.

I added this line to the setMintPrice method to prevent overflowing:
`require(_mintStepPrice < 10000 ether, "mintStepPrice must be less than 10,000 ether.");`

These lines in the setMintPrice method prevent underflowing:
```
uint256 totalStepPrice = mokensLength * _mintStepPrice;
require(totalStepPrice >= _mintPriceOffset, "(mokensLength * mintStepPrice) must be greater than or equal to mintPriceOffset.");
mintPrice = totalStepPrice - _mintPriceOffset;
```

**Comment by nigeon** [comment]
Looks like new code do the job, but still think you should add SafeMath.
New setMintPrice new lines do prevent underflowing.

Eth address: `0x4e1d8d799A589d77891657b3B3A83BE40309634c`

thanks!

**Comment by mudgen** [comment]
Eth sent.
