### ISSUE TITLE
Audit

### ISSUE THREAD

**Issue by JasonCZMeng** [mudgen/mokens-bug-bounty#3]
No problems in the code so far, the whole thing is pretty good. You'll have to give me some time to find more niche problems or quality of life issues.

One minor and rather niche issue I had was that hypothetically if I wanted to mint the max number of Mokens allowed which is 4,294,967,296 to prevent overflow I couldn't do it since your code only allows a value less than MAX_MOKENS and not equal to.

**Comment by JasonCZMeng** [comment]
another note, according according to an interger overflow chart the max value representable for 32bit is 4,294,967,295 as opposed to 4,294,967,296, or am I wrong about something?

**Comment by mudgen** [comment]
Hi Jason, thank you for looking at this! It is a bit tricky. You are very correct that the largest value representable for 32bits is 4,294,967,295, but the max amount of numbers possible with 32bits is one more because 0 is a number too. 

So the max numbers possible is 4,294,967,296 and the largest number possible is 4,294,967,295.  

So when tokenId equals 4,294,967,295 that means that 4,294,967,296 have been created and no more are possible with 32 bits. Good?

**Comment by JasonCZMeng** [comment]
That does clear up a lot thanks.
